### ISSUE TITLE
bug report: export landmark to json, the node value keep the same, and are wrong

### ISSUE THREAD

**Issue by simzhangbest** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#15]
{
                    "id": "12",
                    "label": "RNC",
                    "description": "",
                    "associatedNodeID": "",
                    "position": "",
                    "orientation": [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
                    "selected": true,
                    "locked": true,
                    "visibility": true,
                    "positionStatus": "preview"
                },
                {
                    "id": "13",
                    "label": "ROr",
                    "description": "",
                    "associatedNodeID": "",
                    "position": "",
                    "orientation": [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
                    "selected": true,
                    "locked": true,
                    "visibility": true,
                    "positionStatus": "preview"
                },
                {
                    "id": "14",
                    "label": "RPF",
                    "description": "",
                    "associatedNodeID": "",
                    "position": "",
                    "orientation": [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
                    "selected": true,
                    "locked": true,
                    "visibility": true,
                    "positionStatus": "preview"
                },
                {
                    "id": "15",
                    "label": "UL1O",
                    "description": "",
                    "associatedNodeID": "",
                    "position": "",
                    "orientation": [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
                    "selected": true,
                    "locked": true,
                    "visibility": true,
                    "positionStatus": "preview"
                },

above is part of landmark json file

**Comment by lucanchling** [comment]
Hi @simzhangbest, did you find a solution to it?

**Comment by luciacev** [comment]
reported bug has been resolved in updated ALI_CBCT version.
