### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by simzhangbest** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#17]
as descriped, I use 2080ti 12GB GPU, how can I adjust this param?

**Comment by lucanchling** [comment]
Hi @simzhangbest,
Normally you just have to adjust the GPU usage in the UI (If your using AMASSS)

**Comment by mrtig** [comment]
I have the same issue. It uses all the memory and then wants to use more and gives an error. I set the GPU usage to 1. I resampled the volume to a quite low resolution.
The GPU has 8 GB of RAM.

I don't know what else to try.

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.04 GiB (GPU 0; 8.00 GiB total capacity; 5.17 GiB already allocated; 673.43 MiB free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by cogitas3d** [comment]
I have almost the same error of @mrtig

**Comment by luciacev** [comment]
Because CBCT images have 0.3mm slices or even larger number of cross-sections, we recommend  as requirement at least  12 GB of RAM in your graphics card.

**Comment by cogitas3d** [comment]
@luciacev My GPU have only 11 GB RAM, is it possible solve this? Maybe resampling the CT-Scan?
