### ISSUE TITLE
Update README to improve readability

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#2]
* [x] Add dedicated `Features` section
* [x] Fix list of modules
* [x] Considering removing list of authors and instead add a dedicated `Acknowledgements` section
* [x] Tweak `Requirements` section
* [x] Add `Prerequisites` sections
* [x] Introduce acronyms like `IOS`
* [ ] Use sections like `Panels and their use` and `Use cases` for each module (see example in Slicer at [Docs/user_guide/modules](https://github.com/Slicer/Slicer/tree/main/Docs/user_guide/modules)). For example, see [transforms](https://github.com/Slicer/Slicer/blob/main/Docs/user_guide/modules/transforms.md). Browsing the [Slicer modules documentation](https://slicer.readthedocs.io/en/latest/user_guide/modules/index.html) will help find relevant examples.

### List of Modules

Consider updating this section

https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/5c13f996e1f367e131b2c2279c9b345652e3086f/README.md?plain=1#L12-L14

adding link to `#amasss-module` and `#ali-module`. Referencing the repository implementing the method there will likely confuse the reader.

Consider looking at this README for an example:
https://github.com/KitwareMedical/SlicerPipelines/blob/main/README.md

### Requirements section 

* There is no need to specify `Slicer 5.1.0 or later` as the extension will be available on the relevant Slicer version. Instead, you could consider adding a `History` section mentioning that the extension was first introduced in `Slicer 5.1.0`. For an example of history sections, see:
  * https://github.com/Slicer/SlicerSurfaceToolbox#history
  * https://github.com/Slicer/SlicerDataStore#history
  * https://github.com/Slicer/Slicer-DataStore#history

* Consider text like the following

```
* In addition of the [Slicer System requirements](https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#system-requirements), for best performance, 12GB of memory is recommended.
* :warning: Trained networks are required to be manually downloaded. See requirements section specific to each module.
```

### Prerequisites sections

* Add dedicated `Prerequisites` sections for each module (the current section called `Load models` should then be updated.

**Comment by jcfr** [comment]
After building the module, I realized there is now a `Download latest models` button, this means the documentation should be updated accordingly.

![image](https://user-images.githubusercontent.com/219043/181373508-94435daa-fea4-4de3-8de8-2cf03edfdbb5.png)

**Comment by jcfr** [comment]
Update to mention "module category" and not "option":

![image](https://user-images.githubusercontent.com/219043/181373838-e6359321-7bfa-46ee-b67f-964d1a4e5448.png)

**Comment by Maxlo24** [comment]
Thanks for your feedback. I'll add a `Use cases` section when I'll have some more free time.
