### ISSUE TITLE
VTK error

### ISSUE THREAD

**Issue by manafn** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#29]
Hello everytime when I run the slicer I get this error 
![image](https://user-images.githubusercontent.com/29486466/220043494-67297f8d-b4a3-4d78-b9f3-2a20aa23f31f.png)

**Comment by lucanchling** [comment]
Hi @manafn,
What is exactly your input data? Is it DICOM files? If so what is the architecture of your input directory?

**Comment by manafn** [comment]
![image](https://user-images.githubusercontent.com/29486466/220724658-0f700123-6339-448a-93a6-92c2d6ecfb26.png)

**Comment by lucanchling** [comment]
Ok so the problem might be the architecture of your input directory.
The code has been designed for an input architecture as follow:
![image](https://user-images.githubusercontent.com/72148963/220728634-822de6b8-fbfd-4cf4-97de-e940b7194078.png)
Let me know if this architecture can be easily done...

**Comment by manafn** [comment]
I renamed the files and removed the "export" but same error should I
 change the folder structure also ?
![image](https://user-images.githubusercontent.com/29486466/220734413-02d16f02-03ea-487c-91cb-4956c49a5b2c.png)

**Comment by lucanchling** [comment]
In fact I was telling you to change the architecture (or structure) of your input folder not the naming of the files.
The naming used in the example was only an example. Sorry if it was confusing for you!

**Comment by manafn** [comment]
Thank a million t worked
