### ISSUE TITLE
Associate tooltip with buttons

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#3]
For example, the following should give a hint to the user:

https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/5c13f996e1f367e131b2c2279c9b345652e3086f/AMASSS/Resources/UI/AMASSS.ui#L176-L187

Mousing over `Download latest model` should indicate something like `Initiate download of the trained model (> 1GB) using an URL opened in default system browser`

Same comment for button `Download test scan`

**Comment by Maxlo24** [comment]
Changes have been made.
Thanks
