### ISSUE TITLE
README: Consider referencing some sample data 

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#5]
To allow Slicer users & developers to test the extension, consider referencing sample data in the README.

To further streamline the experience, you could even consider registering custom sample data in your modules. For example, see [here](https://github.com/rbumm/SlicerLungCTAnalyzer/blob/a5700e941d7a2efe3b96a3d721dd4207bbdf12ac/LungCTAnalyzer/LungCTAnalyzer.py#L33-L75)

**Comment by Maxlo24** [comment]
Sample data added in the README
