### ISSUE TITLE
Traceback leaving ALI module

### ISSUE THREAD

**Issue by jamesobutler** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#6]
If I first go into the ALI module, then second enter another module such as the ALI_CBCT or ALI_IOS module I observe the following traceback error in the python console.
```
Traceback (most recent call last):
  File "C:/S5R/Slicer-build/NA-MIC/Extensions-31085/SlicerAutomatedDentalTools/lib/Slicer-5.1/qt-scripted-modules/ALI.py", line 796, in exit
    self.removeObserver(self._parameterNode, vtk.vtkCommand.ModifiedEvent, self.updateGUIFromParameterNode)
  File "C:\S5R\Slicer-build\bin\Python\slicer\util.py", line 2481, in removeObserver
    events = self.__observations[obj]
  File "C:\S5R\python-install\Lib\weakref.py", line 416, in __getitem__
    return self.data[ref(key)]
TypeError: cannot create weak reference to 'NoneType' object
```

**Comment by Maxlo24** [comment]
ALI_CBCT and ALI_IOS are not supposed to be modules, they are scripted CLI. They are not supposed to show up as modules.
Are there changes I need to make to hide them?

**Comment by jamesobutler** [comment]
Scripted CLI is a type of Slicer module. They are loaded in the modules space and you are using them in the ALI scripted loadable Slicer module. As far as I setting a CLI Slicer module to be hidden I'm not sure. I know it is possible for scripted loadable modules. @jcfr Is hiding a scripted CLI module currently supported?

https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/5c13f996e1f367e131b2c2279c9b345652e3086f/ALI/ALI.py#L1153-L1156

![image](https://user-images.githubusercontent.com/15837524/181561046-a390ce3f-b5ea-423a-b18c-3d55aa973220.png)
![image](https://user-images.githubusercontent.com/15837524/181560841-e5e44560-c2e7-486b-b52d-582bd4b859b4.png)

CLI Slicer modules are given an automatically created UI based on the XML parameter file. Users can run the CLI as seen below:
![image](https://user-images.githubusercontent.com/15837524/181561691-8c150ca6-815b-407a-a6cd-c8bbb7b2742d.png)
