### ISSUE TITLE
Consider using latest `monai` version

### ISSUE THREAD

**Issue by jamesobutler** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#7]
Currently if `monai` is not found in Slicer, the CLI are specifying to install version [0.7.0](https://github.com/Project-MONAI/MONAI/releases/tag/0.7.0) (released Sept 2021).  As of adding this extension to the Slicer extensions index, `monai` is now at version [0.9.1](https://github.com/Project-MONAI/MONAI/releases/tag/0.9.1). Since `monai` is getting lots of updates it would be great to stay on top of using the latest versions for future improvements.

https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/5c13f996e1f367e131b2c2279c9b345652e3086f/ALI_CBCT/ALI_CBCT.py#L71-L75

https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/5c13f996e1f367e131b2c2279c9b345652e3086f/ALI_IOS/ALI_IOS.py#L64-L68

https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/5c13f996e1f367e131b2c2279c9b345652e3086f/AMASSS_CLI/AMASSS_CLI.py#L70-L74

**Comment by Maxlo24** [comment]
Hello James,
We are using a UNETR that was trained with the previous  `MONAI` version  [0.7.0](https://github.com/Project-MONAI/MONAI/releases/tag/0.7.0) (released Sept 2021). The recent update changed the UNETR code and we are not able to use the previously trained models. This might be updated in the future when new models will be trained.

Thanks
