### ISSUE TITLE
Teeth segmentation

### ISSUE THREAD

**Issue by bstartek** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#76]
Will there also be a model for teeth segmentation, as it's missing for a complete tool?

**Comment by tschreiner** [comment]
For IOS scans there is a module: https://github.com/DCBIA-OrthoLab/SlicerDentalModelSeg

**Comment by bstartek** [comment]
I am referring to the segmentation of teeth from CBCT (crown + root).

**Comment by Jeanneclre** [comment]
Hello @bstartek 
Did you try to check the box "Use small FOV models". I am seeing a category "Teeth" with Teeth and Root canal.
If you click on "switch tab selection" it selects the Teeth also.
I am not sure about what it does and why it is not available if we don't check the box. If you want to try and give us some feedbacks :)

![Screenshot from 2024-01-24 11-39-11](https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/assets/91120559/a579c561-d180-4537-ac73-26c6698bcd90)

Thank you!
